spring.application.name=ReactSpringSecurityJwt

spring.datasource.url=jdbc:postgresql://localhost:5432/reactsbjwt
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.security.jwt.secret-key=2B7E151628AED2A6ABF7158809CF4F3C2B7E151628AED2A6ABF7158809CF4F3C
application.security.jwt.expiration=86400000

#logging.level.org.springframework.security=DEBUG