spring.application.name=ReactSpringSecurityJwt

spring.datasource.url=jdbc:postgresql://localhost:5433/reactsbjwt
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create

application.security.jwt.secret-key=2B7E151628AED2A6ABF7158809CF4F3C2B7E151628AED2A6ABF7158809CF4F3C
application.security.jwt.expiration=86400000

#logging.level.org.springframework.security=DEBUG